// import Head from 'next/head'
import Image from 'next/image';
import dynamic from 'next/dynamic';
import Script from 'next/script';
import React, { useEffect } from "react";
import Head from 'next/head';
//import foo from '../foo.js';

import Header from '../components/header';
import Banner from '../components/banner';
import Footer from '../components/footer';
import Quote from "../components/quote"; 
import Portfolio from '../components/portfolio';
import About from '../components/about';
import Shop from '../components/shop';
import Newsletter from '../components/newsletter';

export default function Home() {

  return (
    <div>

      <Head>
        <title>Silly Mushroom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>
      <div id="preloder">
        <div className="loader"></div>
      </div>
      <div className="sp-line"></div>


      <Header></Header>
      <Banner></Banner>
      <Quote></Quote>
      <Portfolio></Portfolio>
      <About></About>
      <Shop></Shop>
      <Newsletter></Newsletter>
      <Footer></Footer>



    </div>
  )
}
