import Head from 'next/head'
import Image from 'next/image';
import dynamic from 'next/dynamic';
import Script from 'next/script';
import React, { useState, useEffect } from "react";
//import foo from '../foo.js';

import Header from '../components/header';
import Banner from '../components/banner';
import Footer from '../components/footer';
import ShopBanner from "../components/shopBanner";
import Newsletter from '../components/newsletter';

import { request } from "graphql-request";
import Link from 'next/link';


export default function Shop() {
    const [products, setProducts] = React.useState([]);
    useEffect(() => {
        const fetchProducts = async () => {
            const productData = await request(
                "https://api-ap-south-1.graphcms.com/v2/cl4a15udk1og201w85mlc2gn1/master",
                `
            query getProduct {
                mushrooms {
                  price
                  smallDescription
                  thumbnail {
                    url
                  }
                  title
                  url
                  id
                }
            }
            `
            );

            setProducts(productData);

            //
        };

        fetchProducts();

    }, []);
    console.log("pro", products)
    return (
        <div>

            <Head>
                <title>Silly Mushroom</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    type="text/css"
                    href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
                />
                <link
                    rel="stylesheet"
                    type="text/css"
                    href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
                />
            </Head>
            <div id="preloder">
                <div className="loader"></div>
            </div>
            <div className="sp-line"></div>


            <Header></Header>
            <ShopBanner></ShopBanner>

            <section className="shop-section shop-section-page">
                <div className="container">
                    <div className="row">

                        {products && products.mushrooms && products.mushrooms.map((item) => {
                            return (
                                <div className="col-lg-4 col-sm-6" key={item.id}>
                                    <div className="shop-item">
                                        <img src={item.thumbnail && item.thumbnail.url} alt="" />
                                        <h3> {item.title} </h3>
                                        <h6>Rs. {item.price}</h6>
                                        <Link href={`product/${item.url}`}><a className="add-card">Buy</a></Link>
                                    </div>
                                </div>
                            )
                        })}
                    </div>
                </div>
            </section>
            <Newsletter></Newsletter>
            <Footer></Footer>



        </div>
    )
}
